apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
        app: daystar
        tier: frontend
  template:
    metadata:
      labels:
        app: daystar
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: hebronwatson/daystar-frontend:0.1.0
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000