apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: daystar
    tier: backend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 3002
  selector:
    app: daystar
    tier: backend