apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
        app: daystar
        tier: backend
  template:
    metadata:
      labels:
        app: daystar
        tier: backend
    spec:
      containers:
      - name: backend
        image: hebronwatson/daystar-backend:0.1.1
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3002