version: '2'
services:
  daystar-backend:
    build:
      context: backend
      dockerfile: dockerfile
    container_name: daystar-backend
    image: hebronwatson/daystar-backend:${BACKEND_TAG}
    environment:
      - PORT=${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - daystar
  daystar-frontend:
    build:
      context: frontend
      dockerfile: dockerfile
    container_name: daystar-frontend
    image: hebronwatson/daystar-frontend:${FRONTEND_TAG}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    networks:
      - daystar

networks:
  daystar:
    name: daystar
    driver: bridge